### ISSUE TITLE
Tried to install and I got this error:

### ISSUE THREAD

**Issue by TadFerreira** [wush978/FeatureHashing#117]
g++ -m64 -std=c++0x -I/usr/include/R -DNDEBUG  -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/digest/include" -I"/usr/lib64/R/library/BH/include"   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c RcppExports.cpp -o RcppExports.o
g++ -m64 -std=c++0x -I/usr/include/R -DNDEBUG  -I/usr/local/include -I"/usr/lib64/R/library/Rcpp/include" -I"/usr/lib64/R/library/digest/include" -I"/usr/lib64/R/library/BH/include"   -fpic  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector --param=ssp-buffer-size=4 -m64 -mtune=generic -c as.cpp -o as.o
as.cpp: In function ‘void pair_sort(int*, double*, size_t)’:
as.cpp:26: error: expected primary-expression before ‘[’ token
as.cpp:26: error: expected primary-expression before ‘]’ token
as.cpp:26: error: expected primary-expression before ‘a’
as.cpp:26: error: expected primary-expression before ‘b’
as.cpp: In function ‘size_t merge(int*, double*, size_t)’:
as.cpp:50: warning: comparison between signed and unsigned integer expressions
as.cpp:57: warning: comparison between signed and unsigned integer expressions
make: *** [as.o] Error 1
ERROR: compilation failed for package ‘FeatureHashing’
* removing ‘/u/tadeu/R/x86_64-redhat-linux-gnu-library/3.2/FeatureHashing’
Error: Command failed (1)

**Comment by wush978** [comment]
FeaturrHashing requires c++11, so please use the latest Rtools which supports c++11.
