### ISSUE TITLE
install FeatureHshing package error in linux server

### ISSUE THREAD

**Issue by zy1369834** [wush978/FeatureHashing#118]
Hi, recently I want to install featurehashing package in liunx R. but failed with some error. Could u help me to solve it? thanks

![image](https://cloud.githubusercontent.com/assets/7645535/14346282/d61b8994-fcb1-11e5-8bce-2d073839a22c.png)

**Comment by wush978** [comment]
It requires c++11, so you need to update your gcc to v4.8 at least
