### ISSUE TITLE
MLmetrics pkg should be escaped in examples

### ISSUE THREAD

**Issue by jangorecki** [wush978/FeatureHashing#122]
Hi,
Just came to inform that suggested packages used in examples should be escaped, so not mandatory to run examples. Best way is to use `if (requireNamespace(.)) {_actual_code_}` function. Otherwise you should move `MLmetrics` (and potentially others, `MLmetrics` was first to fail) to imports.

```
* checking examples ... ERROR
Running examples in ‘rFTRLProximal-Ex.R’ failed
The error most likely occurred in:

> ### Name: FTRLProx_cv
> ### Title: FTRL-Proximal Linear Model Cross Validation
> ### Aliases: FTRLProx_cv
> 
> ### ** Examples
> 
> library(FeatureHashing)
> library(data.table)
> library(rBayesianOptimization)
> library(MLmetrics)
Error in library(MLmetrics) : there is no package called ‘MLmetrics’
Execution halted
```

The best way to check is remove all suggested deps and try R CMD check. More details in [R-exts](https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Package-Dependencies).

**Comment by wush978** [comment]
Thanks for your suggestion. I'll check it soon.

**Comment by wush978** [comment]
I cannot find any MLmetrics in the documentation.
I seems like this should be an issue of the package rFTRLProximal
