### ISSUE TITLE
Change the default of `transpose` as FALSE

### ISSUE THREAD

**Issue by wush978** [wush978/FeatureHashing#35]
For normal R user, the default of `transpose` should be `FALSE`.

**Comment by wush978** [comment]
In my opinion, the transposed `dgCMatrix` is more convenient to iterate over instances, so I set the transpose as TRUE in default under latest commit a4153578b0955ff20d594e37313d7e9501a564fe {cran-2015-01-01}.

I was wrong. The glmnet and xgboost use a non-transposed `dgCMatrix` as input, so the normal user probably might want to use a non-transposed one.

**Comment by pommedeterresautee** [comment]
The need to set this parameter to False for xgboost for instance should be indicated in the documentation.

**Comment by wush978** [comment]
Here is an example to demonstrate how to iterate over row and column of `dgCMatrix`.

```r
library(Matrix)
(m <- Matrix(c(0,0,2:0), 3,5))

# iterate over row
for(i in 1:3) {
  # get index of all elements in specific row
  index <- which(m@i == (i - 1))
  # extract column from m@p
  column <- index
  for(j in seq_along(index)) {
    column[j] <- which(m@p + 1 > index[j])[1]
  }
  row <- integer(ncol(m))
  row[column - 1] <- m@x[index]
  print(row)
}

# iterate over column
for(i in 1:5) {
  # get index of all elements in specific column
  index <- if (m@p[i] == m@p[i + 1]) integer(0) else seq(m@p[i], m@p[i + 1] - 1, by = 1)
  row <- m@i[index + 1]
  column <- integer(nrow(m))
  column[row + 1] <- m@x[index + 1]
  print(column)
}
```

As shown above, iterate over column is straight forward, but iterate over row requires some work around.
