### ISSUE TITLE
Argument for enabling binary hashing for sign

### ISSUE THREAD

**Issue by wush978** [wush978/FeatureHashing#39]
Sometimes the user does not concern with collision and we should let them disable binary hashing for speed enhancement

**Comment by wush978** [comment]
For compatibility, the default value should be `TRUE`.

**Comment by pommedeterresautee** [comment]
Having such parameter is Ok for me.

**Comment by pommedeterresautee** [comment]
You may want to document that in most cases collisions are auto magically managed by ML algorithms most of the time, therefore the issue is not that big than what you may imagine.

**Comment by wush978** [comment]
You're right. And I like your comment in https://github.com/wush978/FeatureHashing/issues/49#issuecomment-77775269

Let's rename the argument name as `signed.hash`.
