### ISSUE TITLE
Delete README.Rmd file

### ISSUE THREAD

**Issue by pommedeterresautee** [wush978/FeatureHashing#43]
I don t see the purpose of this file as Github use only the md one.
I don't delete it myself as I may miss something.

Kind regards,
Michael

**Comment by wush978** [comment]
As you have suggested in https://github.com/wush978/FeatureHashing/issues/41#issuecomment-77178420, I am searching for datasets to demonstrate this package. Once I include a dataset, the README.Rmd is required.

Moreover, I think the R building system will ignore it according to .Rbuildignore

Thanks for your suggestion.
