### ISSUE TITLE
Renaming argument `keep.hashing_mapping`

### ISSUE THREAD

**Issue by wush978** [wush978/FeatureHashing#49]
For naming consistency, I think `is.mapping` is a better name.

Also, the users should not be affected seriously because this argument is designed for demonstration. They should not want to use them.

**Comment by wush978** [comment]
ed6e0db0b6222c6f6d4427db11d913cb40b6e9c8

**Comment by pommedeterresautee** [comment]
I would use `create_mapping` instead of is.mapping because for the user when he sets this parameter he answers to the question : do you want to create a mapping?

**Comment by pommedeterresautee** [comment]
I suppose is.xi is related to managing number sign. I don t think it s easy to understand. May be, `signed.hash` would be a better name? And very important: performance vs collision trade-off should be documented IMO.

**Comment by wush978** [comment]
Yes.

Now I want to make the style consistent, so I think `create.mapping` might be better. I'll rename it if you agree.

**Comment by pommedeterresautee** [comment]
_ or . or camelCase, it is up to you :-)
(I prefer camelCase but I come from Java, I may have a bias, I noticed that the point seems to be the most used convention in R)
