### ISSUE TITLE
Default space

### ISSUE THREAD

**Issue by pommedeterresautee** [wush978/FeatureHashing#51]
For Vowpal Wabbit, default space is 2^18
https://github.com/JohnLangford/vowpal_wabbit/wiki/Feature-Hashing-and-Extraction

Is there a reason why default in this package is 2^26? I don t know if there is a reason for the default value of Vowpal but I like the idea doing like them as they have plenty experience in using this trick (adn Vowpal author is one of the author of the main paper introducing hashing trick)
Is there a maximum which should be documented? I think yes it should be the same max as documented for Vowpal.

Kind regards,
Michael

**Comment by wush978** [comment]
I have not seriously thought about the default size. Now I usually use 2^20 just because it is near 10^6.
