### ISSUE TITLE
Non-formula interface of feature hashing

### ISSUE THREAD

**Issue by wush978** [wush978/FeatureHashing#53]
As described in https://github.com/wush978/FeatureHashing/issues/50#issuecomment-77770103, I think we should arrange this feature in a patch.

**Comment by pommedeterresautee** [comment]
FYI code is in the pull request. I used `magrittr`. It adds a dependency but it makes the code much more clear and you can use it everywhere, therefore I think it is ok to add it. Moreover it is installed from Cran so for the user it changes nothing.

**Comment by pommedeterresautee** [comment]
Now you have merged the pull request, this issue can be closed.

**Comment by wush978** [comment]
#48
