### ISSUE TITLE
New names for functions

### ISSUE THREAD

**Issue by pommedeterresautee** [wush978/FeatureHashing#54]
Both function names are not easy to understand. Some idea:
hash_h -> hashed_value (opposite to matrix)
hash_xi -> hash_sign
hashed.model.matrix -> hashed_matrix (switch point to underscore for consistency)
tag -> expand

**Comment by wush978** [comment]
Thanks for the suggestion. I'll rename them all tonight.

**Comment by pommedeterresautee** [comment]
My 2 cents:

I think hash_matrix is better than hash**ed**_matrix, better consistency and make more sense, why used the past (hash**ed**) if we are going to compute the matrix (future)?

Regarding the order hash_matrix vs matrix_hash I think starting by hash is better because all hash functions will be group together in the documentation.

**Comment by wush978** [comment]
For `hashed.model.matrix`, I think the `hashed` is an adjective of `model.matrix`. And the name is more similar to the well-known `model.matrix` and `sparse.model.matrix`.

Therefore, I think we should use the dot style instead of underscore.

**Comment by pommedeterresautee** [comment]
Ok, it makes sense too.
So for consistency, point separator everywhere? like for parameters.

**Comment by wush978** [comment]
Yes. So the dot style should be used consistently in this package.

**Comment by wush978** [comment]
#49

**Comment by wush978** [comment]
For the function name `tag` and `expand`, I think `split` might be more close to its feature.

**Comment by pommedeterresautee** [comment]
I agree
