### ISSUE TITLE
Update author

### ISSUE THREAD

**Issue by wush978** [wush978/FeatureHashing#55]
Dear Michael,

Thanks for your help about FeatureHashing. Would you mind if I put you into the author list as a contributor? If yes, could you give me a pull request to put your self in the DESCRIPTION file? 

Best,
Wush

**Comment by pommedeterresautee** [comment]
Thanks a lot for the offer. I will do a pull request this Week end.

Yesterday I played a lot with your (updated) package and I have finally been able to make the feature importance analysis on a feature hashed dataset and get back the original feature names in the trees of the xgboost model.

Initially I thought to make change to the xgboost source code but it won't be necessary, everything required is already in place.

There is still some process to perform to convert the feature hashed result and get back the correct value names. Would you agree if I add a dedicated function to your package? It makes more sense to put it in your package as it is specific to it.

Regarding plotting a xgboost model based on a feature hashed dataset, I will first need to make change to the xgboost source code before being able to add a function in your package (if you are Ok with that).

Kind regards,
Michael

**Comment by wush978** [comment]
I think it is ok to add a feature ( function ) related to this package. I am looking forward to seeting your PR.
