### ISSUE TITLE
Add a function to extract mapping from hashed Matrix

### ISSUE THREAD

**Issue by pommedeterresautee** [wush978/FeatureHashing#57]
This is a common operation and a dedicated function should exist.
It would be a one line function if I implement it using `magrittr`.

Right now the mapping is stored in the matrix as an attribute. I think it is an issue as it is not very easy to discover (you need to know there is something to look for and call `attributes` function).

I am wondering if it would not be better to add a slot to the existing CSCMatrix class like described [there](https://stat.ethz.ch/pipermail/r-devel/2010-September/058415.html) for instance?

Basically, it (just) requires to add a new class having this slot extending the Matrix ones. If done correctly the user will type the variable name, add @ then type tab key on its keyboard and all the slots will appear, including the mapping (unlike an attribute). The slot will also appear when calling str which is much more usual than calling attributes.

Of course doing such change make it unnecessary to create a new mapping extraction function, keeping the apparent complexity of the package as low as possible (less function, less documentation to write, less documentation to read for the user).

IMO this improvement in the API may be a little bit harder than changing parameter names in functions but would be an interesting improvement. I can take care of it if you want.

Kind regards,
Michaël

**Comment by wush978** [comment]
I assume that the hashed data should contain lots of categorical columns which have a large amount of levels. The user should not only require the column name but also the levels of the categorical data to decode the hashed indices.

**Comment by pommedeterresautee** [comment]
On a toy dataset

```
> library(FeatureHashing)
The default behavior of the hashed.model.matrix is changed:
    - The default output is converted to dgCMatrix
    - The default value of `transpose` is FALSE

> require(xgboost)
Le chargement a nécessité le package : xgboost
> require(Matrix)
Le chargement a nécessité le package : Matrix
> require(data.table)
Le chargement a nécessité le package : data.table
data.table 1.9.4  For help type: ?data.table
*** NB: by=.EACHI is now explicit. See README to restore previous behaviour.
> if (!require('vcd')) install.packages('vcd') 
Le chargement a nécessité le package : vcd
Le chargement a nécessité le package : grid
> data(Arthritis)
> df <- data.table(Arthritis, keep.rownames = F)
> df[,ID:=NULL]
> output_vector = df[,Improved] == "Marked"
> output_vector
 [1] FALSE FALSE FALSE  TRUE  TRUE  TRUE FALSE  TRUE FALSE FALSE FALSE FALSE
[13] FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE
[25]  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE
[37] FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE
[49] FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE  TRUE FALSE FALSE
[61] FALSE FALSE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE  TRUE FALSE FALSE
[73] FALSE FALSE  TRUE FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE  TRUE
> df[,Improved:=NULL]
> h <- hashed.model.matrix(~., df, hash.size = 2^10, create.mapping = T)
> str(h)
Formal class 'dgCMatrix' [package "Matrix"] with 6 slots
  ..@ i       : int [1:336] 0 1 2 3 4 5 6 7 8 9 ...
  ..@ p       : int [1:1025] 0 84 84 84 84 84 84 84 84 84 ...
  ..@ Dim     : int [1:2] 84 1024
  ..@ Dimnames:List of 2
  .. ..$ : chr(0) 
  .. ..$ : chr [1:1024] "1" "2" "3" "4" ...
  ..@ x       : num [1:336] 1 1 1 1 1 1 1 1 1 1 ...
  ..@ factors : list()
> bst <- xgboost(data = h, label = output_vector, max.depth = 4,
+                eta = 1, nthread = 2, nround = 10,objective = "binary:logistic")
[0]	train-error:0.202381
[1]	train-error:0.202381
[2]	train-error:0.202381
[3]	train-error:0.166667
[4]	train-error:0.190476
[5]	train-error:0.178571
[6]	train-error:0.166667
[7]	train-error:0.166667
[8]	train-error:0.166667
[9]	train-error:0.166667
> importance <- xgb.importance(model = bst)
> importance
   Feature       Gain     Cover Frequence
1:     266 0.64592558 0.7617187 0.7333333
2:     207 0.31860953 0.1439262 0.1666667
3:     317 0.03546489 0.0943551 0.1000000
> mapping <- unlist(as.list(attr(m, "mapping")))
Error in as.list(attr(m, "mapping")) : object 'm' not found
> mapping <- unlist(as.list(attr(h, "mapping")))
> m <- mapping %% 2^10
> m[m==266]
Age 
266 
> m[m==207]
TreatmentTreated 
             207 
> m[m==317]
SexMale 
    317 
```

Results are Ok.

Is there a mistake in the way I do it?

**Comment by wush978** [comment]
I re-run your code and the result is ok. 

In the real case there should be hundreds or thousands of levels in a factor. In such case, the auto-completion of `@` might not help a lot. If there are only a small amount of levels, then feature hashing might not be helpful and the `model.matrix` or `sparse.model.matrix` should be used.

This feature is still interesting and I will accept it if you do this because there is no harm.

**Comment by pommedeterresautee** [comment]
Oh sorry I have not been clear, there would be only one variable, `mapping` which would be the named numeric vector like it is today.

**Comment by wush978** [comment]
Oh, sorry that I misunderstand this issue.

IMO, the CSCMatrix should be a pure object representing a sparse matrix with Compressed Sparse Column and a helper function is enough to extract the information of mapping. In general, the `@` should only be used internally and not exposed to the user in S4.

**Comment by wush978** [comment]
How about naming the helper function as `mapping`?

**Comment by pommedeterresautee** [comment]
I would say `hash.mapping` for both consistency and better understanding of the purpose.

It would have two parameters: `matrix` and `space.size`. Size would be set as `Null` by default. If size is provided then the mapping is converted to address by modulo operation.

I am wondering, what is the purpose for the user of having hash without applying the modulo operation? I am not even sure to understand what exactly mean each value. I would say after the modulo, it is a kind of address in the new hashed vector, but the value before?

Kind regards,
Michaël

**Comment by wush978** [comment]
You have a better sense of naming thing than me. 

The composite of `hashed.value` and `module` is the real hashing function of indices. Therefore, I think the better way is to do the module in `hashed.model.matrix`.

**Comment by wush978** [comment]
Since we need to change the `mapping`, I think we could re-design the data structure of `mapping`.

Currently, the `mapping` is an environment of R, and to the best of my knowledge it is a hash table. The time complexity of the query should be `O(1)`.

If we convert it to vector, it should be more convenient to the normal R user because they usually do not familiar with the environment. However, the time complexity becomes `O(n)` where the `n` is the length of the vector. 

So here is a trade off between convenience and the efficiency. How do you think?

I will vote for convenience now because the user should not query the `mapping` rapidly. For me, I only use this feature for introducing FeatureHashing and debugging.

**Comment by pommedeterresautee** [comment]
haha I m tax lawyer, my job is basically to change name of stuff to avoid a specific law :-)
Doing modulo in the matrix would be the best as it means there is no need to type the size elsewhere.

What about `data.table`? I use it all the time, the performance is outstanding and the ease of use is far away in front of vectors / environment / list / whatever.

All the code I have inserted in Xgboost is `data.table` based.

Kind regards,
Michaël

**Comment by pommedeterresautee** [comment]
Do you think a function like that would be ok for you?
```
hash.mapping <- function(x) data.table(do.call(rbind, x), keep.rownames = T)
```

If Ok I can push code + doc

**Comment by wush978** [comment]
It sounds good but we need to check the performance if the `mapping` is large. 

Moreover, I suggest to put the `data.table` into `Suggests` instead of `Depends` or `Imports` because I want to avoid directly depending on the package. If the package is not existed, we could directly return the list or environment to the user.

Thanks for your suggestion.

**Comment by pommedeterresautee** [comment]
Just benchmark my function against the one in the example (on a >100Mb dataset), and mine is a lot slower to extract mapping. Should not be used :-(

**Comment by pommedeterresautee** [comment]
Small perf improvement:
```R
> library("microbenchmark", lib.loc="~/R/win-library/3.1")
> microbenchmark(mapping <- unlist(as.list(attr(hash, "mapping")), recursive = F), times = 10L)
Unit: milliseconds
                                                             expr      min       lq     mean
 mapping <- unlist(as.list(attr(hash, "mapping")), recursive = F) 675.1697 676.1975 709.0103
   median      uq      max neval
 678.4944 684.228 920.8118    10
> microbenchmark(mapping <- unlist(as.list(attr(hash, "mapping")), recursive = T), times = 10L)
Unit: milliseconds
                                                             expr      min      lq     mean
 mapping <- unlist(as.list(attr(hash, "mapping")), recursive = T) 690.6387 693.008 724.5375
   median       uq      max neval
 694.7892 698.6072 928.9548    10

```

**Comment by wush978** [comment]
I'll add some unit tests and close this issue.

**Comment by pommedeterresautee** [comment]
New article interesting to read:
http://jeffreyhorner.tumblr.com/post/114524915928/hash-table-performance-in-r-part-i
