### ISSUE TITLE
Review the examples and README.Rmd

### ISSUE THREAD

**Issue by wush978** [wush978/FeatureHashing#58]

**Comment by pommedeterresautee** [comment]
In readme there is another way to include bib. You can add Yaml code `bibliography: `

You can check there for an example: https://raw.githubusercontent.com/tqchen/xgboost/master/R-package/vignettes/xgboostPresentation.Rmd

To insert a ref in the rmarkdown document you add @reference in your text.

Kind regards,
Michael

**Comment by wush978** [comment]
Thanks for your suggestion. I will use these tool in the vignette. For README.Rmd, I am not sure if it works for generating html file or not.

**Comment by pommedeterresautee** [comment]
If you use Knitr there is no reason YAML code is not interpreted the same way than for a Vignette, isn't it?

**Comment by wush978** [comment]
I see.

By the way, is it ok for me to directly copy the `vignette.css`? Is there any copyright issue?

**Comment by pommedeterresautee** [comment]
Nope, it s a CSS I made for the XGBoost Vignette. So it s under Apache I think.

**Comment by wush978** [comment]
Hmm... I tried, but the `knitr::knit` returned a markdown file which might not fit the CRAN well.

Please let me confirm this again. Is this for vignette or README?

**Comment by pommedeterresautee** [comment]
I used it for the vignette only.

Kind regards,
Michaël
