### ISSUE TITLE
Size of the matrix in memory

### ISSUE THREAD

**Issue by pommedeterresautee** [wush978/FeatureHashing#59]
There is something I am not understanding. 
When I hash a small dataset with a big space (like 2^25) the matrix is big in memory. But it is a sparse dcgMatrix. Why?

In the paper from J. Langford, it says that the sparsity preserved after hashing. Therefore, the very big matrix should be even more empty than the small one. And should not take more space in memory.

What am I missing?

Kind regards,
Michael

**Comment by wush978** [comment]
This is one of the reason why the default argument of `transpose` is `TRUE` before. 

```
> library(FeatureHashing)
> m1 <- hashed.model.matrix(~ ., iris, hash.size = 2^26)
> m2 <- hashed.model.matrix(~ ., iris, hash.size = 2^26, transpose = TRUE)
> object.size(m1)
4483415232 bytes
> object.size(m2)
21472 bytes
> 
```

**Comment by pommedeterresautee** [comment]
But in both cases it's sparse, isn't it?

**Comment by lewis-c** [comment]
Hi both. Thanks for all your great work on FeatureHashing - I've been trying it out for sentiment analysis and I'm very impressed with the performance. I might post a benchmark on Kaggle to spread the word and I'm happy to provide any help you need on examples and documentation.

On this particular issue, don't you need to be careful about using small datasets like Iris to illustrate or test the memory size? With more realistic data, there didn't seem to be any problem when I used the transpose=F version in package 0.8. The data I was using has 25,000 rows and I was using a hash size of 2^16. That would occupy 12GB in a dense matrix and hashed.model.matrix was keeping it down to 50MB.

**Comment by pommedeterresautee** [comment]
@lewis-c I know that on a big dataset you have an important size reduction because the Matrix is smaller anyway (sparse or not). I imagine that for sentiment analysis you need bag of words and therefore the number of features explode. This is the perfect use case for feature hashing.

My point is more about how is it possible to have different size with a simple transpose of a sparse Matrix. Sparsity doesn't change with transposing. And because I finished to have some doubt, I just made a sum on the original sparse matrix and the transposed one, of course the result is the same, so there is no change in sparsity.

May be there is something to do to avoid the memory peak?

Regarding your offer of helping, I want to write a Vignette for this package, can you post code for sentiment analysis with a toy dataset? If you can use Xgboost for the classification part, it would be even better (but absolutely not required). I want to promote the association between the two of them (which are, IMO, built to take care of important dataset, the main weakness of R).

Kind regards,
Michaël

**Comment by lewis-c** [comment]
So, I'm no expert, but having checked the orientation issue with the Matrix package this issue certainly isn't unique to FeatureHashing. For a demo:

```r
library(Matrix)
x <- Matrix(0, nrow = 100, ncol = 100000)
y <- Matrix(0, nrow = 100000, ncol = 100)

object.size(x)
401424 bytes
object.size(y)
1824 bytes
```

As for a Vignette - I'd be happy to help. And I've also been using and impressed by xgboost so I completely understand why you want to promote the two together. Are there any particular aspects of either package you would want to include?

**Comment by pommedeterresautee** [comment]
I wanted to make that test too :-) 
I would be interesting to understand why it works like that. Does `Spam` have the same behavior?

For the Vignette, my idea is to make the same kind of work that for Xgboost.
https://github.com/tqchen/xgboost/tree/master/R-package/vignettes

The idea is to have one (or more to come for xgboost) with parameters explanation and so on, one (or more) to present entire flow for a specific use case, and one for the math explanation (meaning making J. Langford paper more understandable, I read it this WE and it makes reference to concept outside of the paper). Clearly the first two are more important than the third one (IMO).

For Xgboost, you may want to clone the deposit and generate the Vignette yourself to see command results.

Kind regards,
Michaël

**Comment by lewis-c** [comment]
The column-oriented nature is explained here in part:
https://stat.ethz.ch/R-manual/R-devel/library/Matrix/html/CsparseMatrix-class.html

The 'p' vector of the matrix grows in size as the number of columns does, but increasing the number of rows costs almost nothing if they are all sparse.

On the Vignette - perhaps it's best if l produce a rough draft of a simple R file with comments (using FeatureHashing and xgboost), then get your feedback before polishing the formatting.

**Comment by wush978** [comment]
Thanks for your explanation, @lewis-c . 

For a`m x n` sparse matrix with `k` non-zero elements, if we explore the data structure of `dgCMatrix`, the slot `i` and `x` requires `O(k)` space; the slot `j` requires `O(n)` space; the slot `Dim` and `factors` requires `O(1)` space; the slot `Dimnames` requires `O(n) + O(m)` space originally. Therefore, the total space complexity is `O(m) + O(n) + O(k)`. Note that the `O(m)` comes from the `rownames` of the matrix.

However, the `hashed.model.matrix` return a `dgCMatrix` without `rownames`, so the space complexity becomes `O(n) + O(k)`. Therefore, the `transpose` matters if the dimension is imbalanced.

Hope these information helps.

**Comment by wush978** [comment]
For the issues of vignette, I think we should discuss it in #60 . 

For the space complexity, I think it could be written in the documentation of `hashed.model.matrix` or somewhere. How do you think?

**Comment by pommedeterresautee** [comment]
@wush978 When I discovered the behavior I thought I made something bad. The behavior should be specified in the documentation (including basic explanation found by @lewis-c so user won't think it s a bug to fix as I did). 

I would put it in detail part of documentation of `hashed.model.matrix` function (where users will first go when they wonder what happened).

Now I am wondering if we can work on xgboost with a transpose Matrix. I mean, the sparse Matrix is converted in `xgb.DGMatrix` anyway. So may be we can avoid the transpose so we keep the hashed Matrix small during all the process.

**Comment by lewis-c** [comment]
Personally, based on my first impressions of FeatureHashing, I would hesitate before trying to be too clever on this issue. The 'natural' thing users would expect is for the cases to remain as rows and the features as columns, just because that's 'the r way'. And although the link to xgboost is a great thing to prioritise, it should also be kept easy for users to try glmnet or even e1071 for svm.

I quite liked the outline of the changes made in version 0.9, so that the default option is to keep cases as rows and there's no need to do the conversion to the standard sparse Matrix format.

Maybe the option of tranposing to cases as columns / hashes as rows should be left as a power user option? The explanation of the memory benefits can then be explained in that part of the hashed.model.matrix documentation.

**Comment by pommedeterresautee** [comment]
I am more thinking to a dedicated path to transfer the matrix from Feature Hashing to xgboost without memory peak, not a default way of doing. So, I fully agree with you, the results should be easily interpreted.

**Comment by wush978** [comment]
For the dedicated path, I prefer to open an issue in xgboost and we need to confirm with the maintainer of the xgboost. The work should be easier in there. I could also help for developing C++ code to transfer the matrix once I understand the data structure used in xgboost.

**Comment by wush978** [comment]
I will add the information from this issue to the documentation of the `hashed.model.matrix`. Once the documentation is finished, I will close the issue.
