### ISSUE TITLE
Vignette

### ISSUE THREAD

**Issue by wush978** [wush978/FeatureHashing#60]
This package deserve a vignette and I am very very excited that both of @pommedeterresautee  and @lewis-c would like to help.

So far I agree with what @pommedeterresautee mentioned in a discussion about vignette of xgboost: the vignette should focus on how to use the package correctly instead of the mathematics behind the package. 

Because FeatureHashing is only a step of feature extraction, the vignette must include the usage of another machine learning algorithm in another package such as `xgboost` or `glmnet`. Currently I put all algorithms I used before in the README, so I think we could describe more details in the vignette for each of them.

Any suggestion and contribution about vignette are welcome here.

**Comment by pommedeterresautee** [comment]
https://github.com/wush978/FeatureHashing/issues/45

**Comment by pommedeterresautee** [comment]
Possible subjects for the Vignettes:
* Parameters
* Complete use case (for instance: sentiment analysis)
* Mathematical (-> Jang Landford [paper](http://arxiv.org/pdf/0902.2206.pdf) explanation. not urgent)

(From https://github.com/wush978/FeatureHashing/issues/59)

**Comment by lewis-c** [comment]
Just to confirm my comments from #59 : I will draft a sentiment analysis example from start to finish, using FeatureHashing and xgboost. I'm thinking of using the dataset from the Kaggle word2vec competition as I've already tried that privately and I know it performs well. Also, if you would like more people to know about FeatureHashing then by posting it in the Kaggle forum as a benchmark I'm sure we'd generate some interest as the competition is still 'live'.

**Comment by wush978** [comment]
Dear @pommedeterresautee  and @lewis-c, thanks for your proposal and I'm looking forward to get your pull request. But we need to discuss how to work together.

First of all, we should agree with the tool chain of the vignette first. @pommedeterresautee suggests the way xgboost uses (<https://github.com/tqchen/xgboost/tree/master/R-package/vignettes>) and I agree with him because I am familiar with RMarkdown too. 

As a fan of git flow, I prefer to use the git branching as follow. Since the `v0.9` has not been submitted to CRAN yet (I am still reviewing the documentation and I think #59 should be included). IMO the work of vignette should put into the branch `dev/0.9.1`. Therefore, we could start the work of vignette as soon as possible and the work of `v0.9` will not be disturbed.

Once we confirm the topic of vignette, I will open the related issue to discuss the details of the topic.

Please feel free to give any feedback about this.

**Comment by lewis-c** [comment]
Thanks - yes, happy to use the xgboost vignette as a template for ours. I have been using v0.8 of FeatureHashing so far but I can easily switch to using v0.9 for the vignette. And I know the basics of RMarkdown so should be able to learn the rest easily enough.

If I want to use the word2vec data as an example dataset for sentiment analysis, I will have to post a draft version of the vignette on the Kaggle forum first, before we then refine the vignette on github. But that should not be a problem.

**Comment by wush978** [comment]
Sorry that I cannot start working on this issue before next week. Once the build environment is established, I will open the issue for you.

**Comment by wush978** [comment]
<https://github.com/wush978/FeatureHashing/issues/58#issuecomment-81989933>

**Comment by wush978** [comment]
We have two vignettes now, so I will close this issue.
