### ISSUE TITLE
Directly convert the result to `Matrix::dgCMatrix`

### ISSUE THREAD

**Issue by wush978** [wush978/FeatureHashing#7]

**Comment by wush978** [comment]
This is because the returned object in v0.8.1 is a new S4 type `CSCMatrix`. This object is working for my own algorithms.

I expect a normal user will convert it to `Matrix::dgCMatrix` first and pass it to the following algorithm. Therefore, it will be more convenient to return a `dgCMatrix` as default.

**Comment by pommedeterresautee** [comment]
I think that most users will want to perform some ML after transformation, so having a conversion done per default is Ok is if it can be disabled. When do you no need this conversion?

**Comment by wush978** [comment]
The matrix-vector multiplication on `CSCMatrix` is faster than `dgCMatrix`. But the users are required to implement algorithm by their own if they choose to use `CSCMatrix`.

**Comment by pommedeterresautee** [comment]
Ok. This is the kind of information I would put in the detail section of the documentation to explain why such parameter exists.
