### ISSUE TITLE
Dealing with previous seen features

### ISSUE THREAD

**Issue by BlindApe** [wush978/FeatureHashing#77]
Hi,

Hashing in a CTR data context we need the info when and Ad has been printed / clicked before for a user. Is there a way to automatic hash this with formula interface?
This would be equivalent to set a derived feature that for each observation count the previous times the original feature has happened.

Thank you for the package!

**Comment by wush978** [comment]
Could you provide an example of the input data?

FeatureHashing supports split and hash now. Please check `?simulate.split`. Is this what you want?

**Comment by BlindApe** [comment]
Thnak you @wush978 , I understand now how it works.

**Comment by wush978** [comment]
You are welcome.
