### ISSUE TITLE
Bug in existence ?

### ISSUE THREAD

**Issue by pommedeterresautee** [wush978/FeatureHashing#81]
From my understanding, unlike count option, Matrix produced by existence option hashing should be only made of 0 and 1.

If it is true for most of elements, it is not 100% true.
Following I use labeledTrainData.tsv from the Vignette (data from Kaggle).

```R
require(FeatureHashing)
require(Matrix)

setwd("./WHATEVERFOLDER/")
imdb <- read.delim("./labeledTrainData.tsv", quote = "")
d1 <- hashed.model.matrix(~ split(review, delim = " ", type = "existence"),
                          data = imdb, hash.size = 2^16, signed.hash = FALSE)

> sum(d1>1)
[1] 7575
> sum(d1==1)
[1] 3859711
> sum(d1==0)
[1] 1634532714
> sum(d1>2)
[1] 26
> sum(d1>3)
[1] 0
```

For `>1` and `>2`, Is it expected? Does that mean there are collisions?

Kind regards,
Michael

**Comment by wush978** [comment]
Dear @pommedeterresautee ,

Thanks for your report.

At first, I think this is due to collision. However, I need to explore more. The hash mapping cannot be mapped to the original content correctly. I need to explore further.

Wush

**Comment by wush978** [comment]
Yes, I think this is due to collision of the tokens.

A quick checking is increasing the `hash.size` and see if the number of element which is greater than 2 becomes smaller:

```r
d1 <- hashed.model.matrix(~ split(review, delim = " ", type = "existence"),
                          data = imdb, hash.size = 2^16, signed.hash = FALSE,
                          create.mapping = TRUE)
sum(d1 > 1) # 7575
d2 <- hashed.model.matrix(~ split(review, delim = " ", type = "existence"),
                          data = imdb, hash.size = 2^20, signed.hash = FALSE,
                          create.mapping = TRUE)
sum(d2 > 1) # 174
```

This is a bug.

However, I think this behavior is sometimes reasonable if we think the effect is according to the number of `unique` tokens. That is to say, I want to let the user to choose whether they want a absolutely 0/1 result or the number of unique tokens.

Thanks for your report.

**Comment by pommedeterresautee** [comment]
By dividing the matrix by itself we can easily get back the 1/0 matrix. May be a mention in the documentation?

**Comment by wush978** [comment]
Hmm... I think we need to solve this issue fundamentally.

The approach in https://github.com/wush978/FeatureHashing/issues/81#issuecomment-127991881 migh have problem when there is a `split(..., type = "existence")` and split(..., type = "count")`.

I guess we need three types of split.

**Comment by pommedeterresautee** [comment]
3, meaning existence with collisions, without collision, and count?

**Comment by wush978** [comment]
Yes!

**Comment by wush978** [comment]
Now I correct the split of "existence". However, this issue derives the following issues:

- Interaction of split of existence.
- existence without filtering out collision.

**Comment by wush978** [comment]
I think this issue is basically resolved. @pommedeterresautee , how do you think?
