### ISSUE TITLE
Default `signed.hash` becomes FALSE

### ISSUE THREAD

**Issue by wush978** [wush978/FeatureHashing#91]
I think the `signed.hash` is surprising to lots of R users.

Maybe we should turn off it by default.

**Comment by lewis-c** [comment]
I agree that it would be worth considering this. It's possible at the moment to use the signed.hash without realiing you are doing so and I imagine that a lot of users only take the trouble to understand it once they have generated a surprising result for themselves. Or perhaps I should admit that was the route I took as someone new to all of these concepts.

**Comment by wush978** [comment]
Thanks for your reply, @lewis-c !

Let's do this.
