### ISSUE TITLE
Is it possible to expose C++ API for string hashing?

### ISSUE THREAD

**Issue by dselivanov** [wush978/FeatureHashing#96]
@wush978, hi. Thank you for your great work!
I'm working on [tmlite](https://github.com/dselivanov/tmlite) package, which already has option for construction of hash corpora from text. But for now I'm using `std::hash` which is platform-dependent and I believe can produce worser distribution then `murmurhash3`. Also at the moment I don't use second hash function for reducing probability of collision. Of course I can reinvent the wheel and write it from scratch using `digest` header, but I think it will be better to use your solution. 
Is it possible and ok for you? Any ideas are very appreciated.

Thanks in advance.

**Comment by wush978** [comment]
Dear @dselivanov, 

Please check the commit history: https://github.com/wush978/FeatureHashing/commit/ea7cc034b0dbdfa6fc742fcebaa7dc4025f5364e#diff-db1530bbc203e0f7ac9d8b844d1f63a3

This is how I call the murmurhash3 from `digest`. 

By the way, I am designing a new interface which allows user to register C call back and corresponding special keyword. Then, the user could use them in the formula interface such as:

```
f <- get_function(...)
register_special("jieba", f)
m <- hashed.model.matrix( ~ jieba(review), ...)
```

Maybe it might help you and your package.

**Comment by dselivanov** [comment]
@wush978 , thank you! I'll check. Can we keep this open for some time (in case I'll have questions)?

**Comment by wush978** [comment]
No problem.

**Comment by dselivanov** [comment]
@wush978, thank you very much, I'm successfully switched to `PMurHash32` from `digest` package and will close this issue soon (I want to do by it by commit).
Only one more question, why you keep [digestlocal.h](https://github.com/wush978/FeatureHashing/blob/master/src/digestlocal.h) header file in FeatureHashing repository?  [comments in pmurhashAPI.h](https://github.com/eddelbuettel/digest/blob/master/inst/include/pmurhashAPI.h#L33) suggest only to add `#include <pmurhashAPI.h>` and this works for me fine. May be I missed something?
> 
      1) In your package, add 'LinkingTo: digest' to the DESCRIPTION file.
         This ensure that R will know the path to this file.
      2) In your source code, add '#include <pmurhashAPI.h>'
         This ensures the compiler knows the declaration of the function 
         interface.
      3) In your package's source code, call 'res = PMurHash32(seed,
         key, len);' where res and seed are of type MH_UINT32 (which
         is defined appropriately below).
      4) The local function here sets a static pointer to the actual
         MurmurHash32 implementation in this package. R takes care of
         the function registration, export and import --- meaning that
         no build-time linking of your package is needed resulting in
         simpler and more robust build steps.

**Comment by wush978** [comment]
You are right. the `digestlocal.h` is redundant. I will remove it in the future.

**Comment by wush978** [comment]
Dear @dselivanov 

I was wrong. The `digestlocal.h` is necessary. That is because the definition of `PMurHash32` is in `pmurhashAPI.h`. Therefore, if you include this file several times, there will be a linking error of : `multiple definition of `PMurHash32'`.
